{{- if and .Values.litellm.enabled .Values.litellm.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.litellm.serviceAccount.name | default (printf "%s-litellm" .Release.Name) }}
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.litellm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
