"""Scope approval idempotency to a generated plan revision.

Revision ID: 20260719_06
Revises: 20260719_05
Create Date: 2026-07-19
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "20260719_06"
down_revision = "20260719_05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Make regenerated byte-identical plans distinct approval artifacts."""

    op.add_column(
        "supervisor_runs",
        sa.Column("plan_revision", sa.Integer(), nullable=False, server_default="0"),
    )
    op.execute("UPDATE supervisor_runs SET plan_revision = 1 WHERE plan_artifact_ref IS NOT NULL")
    op.add_column("plan_approval_decisions", sa.Column("plan_revision", sa.Integer(), nullable=True))
    op.execute("UPDATE plan_approval_decisions SET plan_revision = 1 WHERE plan_revision IS NULL")
    op.alter_column("plan_approval_decisions", "plan_revision", nullable=False)
    op.drop_constraint("plan_approval_idempotency", "plan_approval_decisions", type_="unique")
    op.create_unique_constraint(
        "plan_approval_revision_idempotency",
        "plan_approval_decisions",
        ["run_id", "plan_revision", "idempotency_key"],
    )


def downgrade() -> None:
    """Refuse destructive schema rollback; restore through a compatible application release."""

    raise RuntimeError("Cogito supervisor migrations are forward-only and cannot be downgraded")
